### ISSUE TITLE
Hyperlinks for propertyViews having an action installed aren't deactivated when a gate deactivate the action.

### ISSUE THREAD

**Issue by Dealus** [jspresso/jspresso-ce#10]
When installing an action on a propertyView, an hyper link is displyaed in UI. If a gate deactivate the action, the hyper link remains visible.

Tested with a booleanActionabilityGate.

**Comment by Dealus** [comment]
Furthermore, installing a booleanActionabilityGate on this kind of propertyView action deactivates the action no matter what the return value of the gate is (true or false -> Locked).

**Comment by vvandens** [comment]
Whether the hyper link actually triggers the action is based on the action being enabled or not. On a form view, the hyper link state is correctly reflected based on the state of the action (computed according to its gates).
The problem gets more complicated when on a grid view since a single action is installed for a given grid column (and not 1 action per line). In that case, the (column) action enable state is determined when the selection changes on the grid, and it's not possible to have a different state at the same time for different lines. That's why the hyper link is always rendered and only triggers something when the action is enabled **when** the user clicks it, i.e. after having selected the row. Computing the hyper link state line by line would introduce a deep change in the design and a serious performance impact.
That's why we won't *fix* it.
Moreover, we have not verified the second problem so I presume it's linked to your code.
