### ISSUE TITLE
Slowness on uploading text files

### ISSUE THREAD

**Issue by ImadBABA** [jspresso/jspresso-ce#242]
When uploading files on HTML5 Jspresso version, we note some slowness :
1- When file size > 1 Mo and < 5 Mo,the file take a lot of time to upload, may be an asynchrone solution can make the upload more responsive.
2 - When file size > 5, the upload take a lot of time to get the error that file size is not allowed for upload, may be a client check can help to get directly the popup error.

thanks for help.

**Comment by vvandens** [comment]
The file size is now controlled on the client before being sent to the server.
I'm not for making this asynchronous since it would change the overall behavior.
If text files are used, maybe you could ask the user to zip them before sending and unzip them on the server before processing them (with an interceptor for instance) ?
