### ISSUE TITLE
Do not force Spring 'class' attribut when using 'parent' SJS attribut

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#499]
For example for propertyView...

**Comment by vvandens** [comment]
SJS-3.1.8

**Comment by vvandens** [comment]
This introduces too many regressions. For instance, when using templates for views, setting for instance (as in HRSample) :

```
template 'form',
    parent: 'decoratedView',
    labelsPosition: 'ABOVE',
    columnCount: 2

template 'table',
    parent: 'decoratedView'

template 'tree',
    parent: 'decoratedView'

template 'listView',
    parent: 'decoratedView'
```

The class is not set in parent and must be explicitly defined in the generated Spring.

The solution to your problem is to use paramsets for instance or templates in order to fix your custom class into the SJS components.
